### PR TITLE
Fix bugs in tests

### PR DESCRIPTION
**Pull request by noahhaasis**
I found some bugs doing the challenge in all languages except swift.
I also noticed that in some implementations the last row of the logo has to end with a '\n' but not in all.
But since this is not documented I didn't fix it.

### CODE REVIEW

**Comment by moelders** [comment]
Thanks, @noahhaasis for the PR, we are going to check the changes.

**Comment by josete89** [comment]
Sorry for the delay. LGTM

**Review by josete89 — APPROVED** [review]
LGTM

**Comment by moelders** [comment]
Thank @noahhaasis and @josete89!

**Pull request merged**
